#### 1. Write a Python Program to Add two Matrices ?

In [1]:
def addMatrices(a,b):
    print(f'Inputs: {a},{b}')
    if len(a) == len(b):
        out_matrix = []
        for ele in range(len(a)):
            if len(a[ele]) == len(b[ele]):
                out_matrix.append([])
                for sub_ele in range(len(a[ele])):
                    out_matrix[ele].append(a[ele][sub_ele]+b[ele][sub_ele])
            else:
                print('Both Matrices must contains same no of rows and columns') 
    else:
        print('Both Matrices must contains same no of rows and columns')
    print(f'Output: {out_matrix}')

addMatrices([[1,2,3],[4,5,6],[7,8,9]],[[9,8,7],[6,5,4],[3,2,1]])
addMatrices([[2,3,5],[1,1,1],[2,2,2]],[[4,3,5],[1,2,3],[3,2,1]])

Inputs: [[1, 2, 3], [4, 5, 6], [7, 8, 9]],[[9, 8, 7], [6, 5, 4], [3, 2, 1]]
Output: [[10, 10, 10], [10, 10, 10], [10, 10, 10]]
Inputs: [[2, 3, 5], [1, 1, 1], [2, 2, 2]],[[4, 3, 5], [1, 2, 3], [3, 2, 1]]
Output: [[6, 6, 10], [2, 3, 4], [5, 4, 3]]


#### 2. Write a Python Program to Multiply two Matrices ?

In [5]:
import numpy as np

def main():
    # Example matrices (you can replace these with your own matrices)
    matrix1 = np.array([[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]])

    matrix2 = np.array([[9, 8, 7],
                        [6, 5, 4],
                        [3, 2, 1]])

    try:
        result = np.dot(matrix1, matrix2)
        print(result)
    except ValueError as e:
        print("Error:", e)

if __name__ == "__main__":
    main()

[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


#### 3. Write a Python Program to transpose a Matrix ?

In [3]:
def main():
    # Example matrix (you can replace this with your own matrix)
    matrix = np.array([[1, 2, 3],
                       [4, 5, 6],
                       [7, 8, 9]])

    transposed_matrix = np.transpose(matrix)  # Or you can use matrix.T

    print("Original Matrix:")
    print(matrix)
    print("\nTransposed Matrix:")
    print(transposed_matrix)

if __name__ == "__main__":
    main()


[[1, 2, 3], [4, 5, 6], [7, 8, 9]] -> [[1, 4, 7], [2, 5, 8], [3, 6, 9]]
[[1, 2], [4, 5], [7, 8]] -> [[1, 4, 7], [2, 5, 8]]
[[1, 2, 3], [4, 5, 6]] -> [[1, 4], [2, 5], [3, 6]]


#### 4. Write a Python Program to sort Words in an Alphabatical Order ?

In [1]:
def sortString():
    in_string = "i am dilip"
    sorted_list = sorted(in_string.split(' '))
    print(' '.join(sorted_list))

sortString()

am dilip i


#### 5. Write a Python Program to remove Punctuations From a String ?

In [3]:
def removePunctuatuions():
    punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    in_string = '"Full Stacks DS 2.0" @ Ineuron"'
    out_string = ''
    for ele in in_string:
        if ele not in punctuations:
            out_string += ele
    print(out_string)
    
removePunctuatuions()

Full Stacks DS 20  Ineuron
